name: checkstyle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Env setup
        run: |
          mkdir -p /opt/lib
          wget -q -O /opt/lib/checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.6/checkstyle-10.12.6-all.jar
          cd "${GITHUB_WORKSPACE}"

      - name: Run Checkstyle
        run: |
          exec java -jar /opt/lib/checkstyle.jar "." -c "checkstyle_checks.xml" -f xml > results.xml

      - name: Print Results
        run: echo "$(cat results.xml)"

      - name: Check Results
        run:  |
          if grep -q error results.xml; then
            echo "Checkstyle found an error - look at the logs under Print Results for details"
            exit 1
          else
            echo "No errors found!"
          fi

      # Run Reviewdog on Checkstyle results and add PR comments
      - name: Run Reviewdog on Checkstyle results
        uses: reviewdog/action@v2
        with:
          name: checkstyle
          reporter: github-pr-review
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: checkstyle
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}