name: Checkstyle with Reviewdog

on: [pull_request]

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1.3.2

      - name: Run Checkstyle and reviewdog
        run: |
          ./gradlew checkstyleMain || true
          find . -name 'checkstyle-result.xml' -exec cat {} + \
            | reviewdog -f=checkstyle -reporter=github-pr-review -level=error
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}-setup@v1.3.2